# Generated by Django 4.2.7 on 2024-02-16 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('tezina_izrade', models.CharField(max_length=20)),
                ('vrijeme_izrade', models.TimeField()),
                ('opis', models.TextField()),
                ('vrijeme_objave', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
