# Generated by Django 4.2.7 on 2024-02-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_kategorije', models.CharField(max_length=100)),
                ('opis_kategorije', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=25)),
                ('prezime', models.CharField(max_length=30)),
                ('autor_recepti', models.ManyToManyField(to='main.recept')),
            ],
        ),
    ]
