# Generated by Django 4.2.7 on 2024-02-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kategorija_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='autor_recepti',
        ),
        migrations.AddField(
            model_name='recept',
            name='autor_recepta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recept',
            name='kategorije',
            field=models.ManyToManyField(to='main.kategorija'),
        ),
    ]
