# Generated by Django 4.2.7 on 2024-02-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_autor_autor_recepti_recept_autor_recepta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='kategorije',
        ),
        migrations.AddField(
            model_name='recept',
            name='kategorija',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.kategorija'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Savjeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_savjeta', models.TextField()),
                ('autori', models.ManyToManyField(to='main.autor')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recept')),
            ],
        ),
    ]
