# Generated by Django 4.2.7 on 2024-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_recept_kategorije_recept_kategorija_savjeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='savjeti',
            name='naslov',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
