# Generated by Django 4.2.7 on 2024-02-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_savjeti_naslov'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritivneInformacije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalorije', models.IntegerField()),
                ('proteini', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ugljikohidrati', models.DecimalField(decimal_places=2, max_digits=5)),
                ('masti', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritivne_informacije', to='main.recept')),
            ],
        ),
    ]
